export default [
  '25 de Mayo',
  '28 de Julio',
  '7 de Abril',
  '9 de Julio',
  'Aarón Castellanos',
  'Abdón Castro Tolay',
  'Abra Pampa',
  'Abralaite',
  'Abramo',
  'Acebal',
  'Acheral',
  'Achiras',
  'Aconquija',
  'Adelia María',
  'Adolfo Alsina',
  'Adolfo Gonzales Chaves',
  'Adolfo Van Praet',
  'Agua Dulce y la Soledad',
  'Agua de Oro',
  'Aguada Cecilio',
  'Aguada Guzman',
  'Aguada San Roque',
  'Aguada de Guerra',
  'Aguaray',
  'Aguará Grande',
  'Aguas Calientes',
  'Agustoni',
  'Alba Posse',
  'Albardón',
  'Albarellos',
  'Alberti',
  'Alcira',
  'Alcorta',
  'Aldao',
  'Aldea Beleiro',
  'Aldea Epulef',
  'Aldea Santa María',
  'Alejandra',
  'Alejandro Roca',
  'Alejo Ledesma',
  'Algarrobo del Águila',
  'Alicia',
  'Allen',
  'Almafuerte',
  'Almirante Brown',
  'Alpa Corral',
  'Alpachiri y el Molino',
  'Alpachiri',
  'Alta Gracia',
  'Alta Italia',
  'Alto Alegre',
  'Alto Pelado',
  'Alto Pencoso',
  'Alto Río Senguer',
  'Alto Verde y los Guchea',
  'Alto de los Quebrachos',
  'Altos de Chipión',
  'Aluminé',
  'Alvear',
  'Amaicha del Valle',
  'Amberes',
  'Amboy',
  'Ambrosetti',
  'Ambul',
  'Ameghino',
  'Amenábar',
  'Ana Zumarán',
  'Ancajuli',
  'Ancasti',
  'Anchorena',
  'Andacollo',
  'Andalgalá',
  'Angaco',
  'Angastaco',
  'Angeloni',
  'Anguil',
  'Angélica',
  'Animaná',
  'Anisacate',
  'Antofagasta de la Sierra',
  'Apolinario Saravia',
  'Apóstoles',
  'Arata',
  'Arauco',
  'Arcadia',
  'Arequito',
  'Arias',
  'Aristóbulo del Valle',
  'Arizona',
  'Arminda',
  'Armstrong',
  'Arocena',
  'Arrayanal',
  'Arrecifes',
  'Arroyito',
  'Arroyo Aguiar',
  'Arroyo Cabral',
  'Arroyo Ceibal',
  'Arroyo Leyes',
  'Arroyo Seco',
  'Arroyo Ventana',
  'Arroyo del Medio',
  'Arroyo los Berros',
  'Arroyo los Patos',
  'Arrufo',
  'Arteaga',
  'Assunta',
  'Atahona',
  'Ataliva Roca',
  'Ataliva',
  'Aurelia',
  'Ausonia',
  'Avellaneda',
  'Avia Terai',
  'Ayacucho',
  'Azara',
  'Azul',
  'Añelo',
  'Bagual',
  'Bahía Blanca',
  'Bajada del Agrio',
  'Balcarce',
  'Balde',
  'Ballesteros Sud',
  'Ballesteros',
  'Balnearia',
  'Baradero',
  'Barrancas',
  'Barranqueras',
  'Barrios',
  'Basail',
  'Batavia',
  'Bauer y Sigel',
  'Bañado de Soto',
  'Beazley',
  'Bell Ville',
  'Bella Italia',
  'Bella Vista',
  'Belén',
  'Bengolea',
  'Benito Juárez',
  'Benjamin Araoz y el Tajamar',
  'Benjamín Gould',
  'Berabevú',
  'Berazategui',
  'Berisso',
  'Berna',
  'Bernardo Larroude',
  'Bernardo de Irigoyen',
  'Bernasconi',
  'Berrotarán',
  'Berón de Astrada',
  'Bialet Massé',
  'Bigand',
  'Bolívar',
  'Bombal',
  'Bonpland',
  'Bouquet',
  'Bouwer',
  'Bragado',
  'Brandsen',
  'Brinkmann',
  'Buchardo',
  'Buen Pasto',
  'Buena Esperanza',
  'Buena Vista',
  'Bulnes',
  'Bustinza',
  'Buta Ranquil',
  'Caa Yarí',
  'Cabal',
  'Cabalango',
  'Cachi',
  'Cacique Ariacaiquín',
  'Cafayate',
  'Cafferata',
  'Caimancito',
  'Calchaquí',
  'Calchín Oeste',
  'Calchín',
  'Caleufú',
  'Calilegua',
  'Calingasta',
  'Calmayo',
  'Camarones',
  'Camilo Aldao',
  'Caminiaga',
  'Campana',
  'Campo Andino',
  'Campo Grande',
  'Campo Largo',
  'Campo Piaggio',
  'Campo Quijano',
  'Campo Ramón',
  'Campo Santo',
  'Campo Viera',
  'Canals',
  'Candelaria Sud',
  'Candelaria',
  'Candioti',
  'Cangrejillos',
  'Capayán',
  'Capilla de los Remedios',
  'Capilla del Carmen',
  'Capilla del Monte',
  'Capilla del Sitón',
  'Capioví',
  'Capital',
  'Capitan Caceres',
  'Capitán Bermúdez',
  'Capitán General B. O\'Higgins',
  'Capitán Sarmiento',
  'Capitán Solari',
  'Capivara',
  'Caraguatay',
  'Carcarañá',
  'Carlos Casares',
  'Carlos Pellegrini',
  'Carlos Tejedor',
  'Carmen de Areco',
  'Carmen del Sauce',
  'Carmen',
  'Carnerillo',
  'Carolina',
  'Carpinteria',
  'Carrenleufú',
  'Carreras',
  'Carrilobo',
  'Carrizales',
  'Carro Quemado',
  'Casa Grande',
  'Casa de Piedra',
  'Casalegno',
  'Casas',
  'Casilda',
  'Caspalá',
  'Castelar',
  'Castellanos',
  'Castelli',
  'Castro Barros',
  'Catriel',
  'Catriló',
  'Catua',
  'Caucete',
  'Cavanagh',
  'Caviahue-Copahue',
  'Cavour',
  'Cayastacito',
  'Cayastá',
  'Caá Catí',
  'Cañada Ombú',
  'Cañada Rica',
  'Cañada Rosquín',
  'Cañada de Gómez',
  'Cañada de Luque',
  'Cañada de Machado',
  'Cañada de Río Pinto',
  'Cañada del Sauce',
  'Cañada del Ucle',
  'Cañuelas',
  'Ceballos',
  'Centenario',
  'Centeno',
  'Cepeda',
  'Ceres',
  'Cerrillos',
  'Cerro Azul',
  'Cerro Centinela',
  'Cerro Colorado',
  'Cerro Corá',
  'Cervantes',
  'Cevil Redondo',
  'Chabas',
  'Chacabuco',
  'Chacharramendi',
  'Chaján',
  'Chalacea',
  'Chamical',
  'Chancaní',
  'Chapuy',
  'Charadai',
  'Charata',
  'Charbonier',
  'Charras',
  'Chascomús',
  'Chavarría',
  'Chazón',
  'Chañar Ladeado',
  'Chañar Viejo',
  'Chichinales',
  'Chicoana',
  'Chilecito',
  'Chilibroste',
  'Chimbas',
  'Chimpay',
  'Chipauquil',
  'Chivilcoy',
  'Choele Choel',
  'Cholila',
  'Choromoro',
  'Chorotis',
  'Chorriaca',
  'Chos Malal',
  'Chovet',
  'Christophersen',
  'Chucul',
  'Churqui Cañada',
  'Chuña Huasi',
  'Chuña',
  'Cieneguillas',
  'Ciervo Petiso',
  'Cinco Saltos',
  'Cintra',
  'Cipolletti',
  'Ciudacita',
  'Ciénaga del Coro',
  'Clason',
  'Clemente Onelli',
  'Clorinda',
  'Colalao del Valle',
  'Colan Conhué',
  'Colazo',
  'Colombres',
  'Colonia Alberdi',
  'Colonia Aldao',
  'Colonia Almada',
  'Colonia Ana',
  'Colonia Anita',
  'Colonia Aurora',
  'Colonia Barge',
  'Colonia Barón',
  'Colonia Belgrano',
  'Colonia Benitez',
  'Colonia Bicha',
  'Colonia Bigand',
  'Colonia Bismarck',
  'Colonia Bossi',
  'Colonia Bremen',
  'Colonia Carlos Pellegrini',
  'Colonia Caroya',
  'Colonia Cello',
  'Colonia Delicia',
  'Colonia Dolores',
  'Colonia Durán',
  'Colonia Italiana',
  'Colonia Iturraspe',
  'Colonia Libertad',
  'Colonia Liebig\'s',
  'Colonia Margarita',
  'Colonia Marina',
  'Colonia Mascias',
  'Colonia Pando',
  'Colonia Pastoril',
  'Colonia Polana',
  'Colonia Popular',
  'Colonia Prosperidad',
  'Colonia Raquel',
  'Colonia Rosa',
  'Colonia San Bartolomé',
  'Colonia San José',
  'Colonia San Pedro',
  'Colonia Santa María',
  'Colonia Santa Rosa',
  'Colonia Tirolesa',
  'Colonia Valtelina',
  'Colonia Vicente Agüero',
  'Colonia Victoria',
  'Colonia Videla',
  'Colonia Vignaud',
  'Colonia Wanda',
  'Colonia la Clara',
  'Colonia las Cuatro Esquinas',
  'Colonia las Pichanas',
  'Colonias Elisa',
  'Colonias Unidas',
  'Colón',
  'Comallo',
  'Comandante A. Guacurary',
  'Comandante Fontana',
  'Comechingones',
  'Comico',
  'Comodoro Rivadavia',
  'Comuna Villa Belgrano',
  'Cona Niyeu',
  'Concaran',
  'Concepción de la Sierra',
  'Concepción del Bermejo',
  'Concepción',
  'Conhelo',
  'Conlara',
  'Constanza',
  'Contralmirante Cordero',
  'Copacabana',
  'Coranzuli',
  'Corcovado',
  'Coronda',
  'Coronel Arnold',
  'Coronel Baigorria',
  'Coronel Belisle',
  'Coronel Bogado',
  'Coronel Domínguez',
  'Coronel Dorrego',
  'Coronel Du Graty',
  'Coronel Felipe Varela',
  'Coronel Fraga',
  'Coronel Hilario Lagos',
  'Coronel Moldes',
  'Coronel Pringles',
  'Coronel Suárez',
  'Coronel de Marina Leonardo Rosales',
  'Corpus',
  'Corral Quemado',
  'Corral de Bustos',
  'Corralito',
  'Correa',
  'Corrientes',
  'Cortaderas',
  'Corzuela',
  'Cosquín',
  'Costasacate',
  'Cote Lai',
  'Covunco Abajo',
  'Coyuco-Cochico',
  'Crispi',
  'Cruz Alta',
  'Cruz de Caña',
  'Cruz de los Milagros',
  'Cruz del Eje',
  'Cuchillo Có',
  'Cuesta Blanca',
  'Cululú',
  'Curupaity',
  'Curuzú Cuatiá',
  'Cushamen',
  'Cusi Cusi',
  'Cutral Có',
  'Córdoba',
  'Daireaux',
  'Dalmacio Vélez',
  'Darwin',
  'Del Campillo',
  'Delfin Gallo',
  'Desaguadero',
  'Despeñaderos',
  'Desvío Arijón',
  'Devoto',
  'Deán Funes',
  'Diego de Alvear',
  'Diego de Rojas',
  'Dina Huapi',
  'Dique Chico',
  'Dique Florentino Ameghino',
  'Doblas',
  'Doctor Ricardo Rojas',
  'Dolavon',
  'Dolores',
  'Dorila',
  'Dos Arroyos',
  'Dos Rosas y la Legua',
  'Dos de Mayo',
  'Dr. Atilio Oscar Viglione',
  'Díaz',
  'Eduardo Castex',
  'Egusquiza',
  'El Aguilar',
  'El Alcázar',
  'El Alto',
  'El Arazá',
  'El Arañado',
  'El Bolson',
  'El Bordo',
  'El Bracho y el Cevilar',
  'El Brete',
  'El Cadillal',
  'El Cain',
  'El Carmen',
  'El Carril',
  'El Cercado',
  'El Chacho',
  'El Chañar',
  'El Cholar',
  'El Colorado',
  'El Crispín',
  'El Cuy',
  'El Cóndor',
  'El Fortín',
  'El Fuerte',
  'El Galpón',
  'El Hoyo',
  'El Huecú',
  'El Jardín',
  'El Maitén',
  'El Manantial',
  'El Manso',
  'El Manzano',
  'El Mojon',
  'El Mollar',
  'El Naranjito',
  'El Naranjo y el Sunchal',
  'El Piquete',
  'El Polear',
  'El Potrero',
  'El Puestito',
  'El Quebrachal',
  'El Rabón',
  'El Rastreador',
  'El Rodeo',
  'El Sacrificio',
  'El Sauce',
  'El Sauzalito',
  'El Soberbio',
  'El Sombrerito',
  'El Tala',
  'El Talar',
  'El Timbo',
  'El Trapiche',
  'El Trébol',
  'El Tío',
  'El Volcan',
  'Eldorado',
  'Elena',
  'Elisa',
  'Elortondo',
  'Embajador Martini',
  'Embalse',
  'Embarcación',
  'Emilia',
  'Empalme San Carlos',
  'Empalme Villa Constitución',
  'Empedrado',
  'Enrique Urien',
  'Ensenada',
  'Epuyén',
  'Escaba',
  'Escobar',
  'Esmeralda',
  'Esperanza',
  'Espinillo',
  'Esquel',
  'Esquina y Mancopa',
  'Esquina',
  'Estacion Araoz y Tacanas',
  'Estación Clucellas',
  'Estación General Paz',
  'Estación Juárez Celman',
  'Estación Torrent',
  'Estancia Grande',
  'Estancia Vieja',
  'Estancia de Guadalupe',
  'Estanislao del Campo',
  'Esteban Echeverría',
  'Esteban Rams',
  'Esther',
  'Etruria',
  'Eufrasio Loza',
  'Eusebia y Carolina',
  'Eustolia',
  'Exaltación de la Cruz',
  'Ezeiza',
  'Fachinal',
  'Facundo',
  'Falda del Carmen',
  'Falucho',
  'Famatina',
  'Felicia',
  'Felipe Yofré',
  'Fiambalá',
  'Fidela',
  'Fighiera',
  'Firmat',
  'Florencia',
  'Florencio Varela',
  'Florentino Ameghino',
  'Fontana',
  'Formosa',
  'Fortin el Patria',
  'Fortuna',
  'Fortín Lugones',
  'Fortín Olmos',
  'Fraga',
  'Fraile Pintado',
  'Franck',
  'Fray Luis Beltrán',
  'Fray Mamerto Esquiú',
  'Freyre',
  'Frontera',
  'Fuentes',
  'Fuerte Esperanza',
  'Funes',
  'Gaboto',
  'Gaiman',
  'Galisteo',
  'Gan Gan',
  'Gancedo',
  'Garabato',
  'Garibaldi',
  'Garmendia',
  'Garruchos',
  'Garuhapé',
  'Garupá',
  'Gastona y Belicha',
  'Gastre',
  'Gato Colorado',
  'Gdor. Piedrabuena',
  'General Acha',
  'General Alvarado',
  'General Alvear',
  'General Arenales',
  'General Baldissera',
  'General Ballivián',
  'General Belgrano',
  'General Cabrera',
  'General Campos',
  'General Capdevila',
  'General Deheza',
  'General Fotheringham',
  'General Gelly',
  'General Guido',
  'General Güemes',
  'General J. J. Urquiza',
  'General Juan Facundo Quiroga',
  'General Juan Madariaga',
  'General Lagos',
  'General Lamadrid',
  'General Lavalle',
  'General Levalle',
  'General Lucio Victorio Mansilla',
  'General Mosconi',
  'General Ocampo',
  'General Paz',
  'General Pico',
  'General Pinedo',
  'General Pinto',
  'General Pizarro',
  'General Pueyrredón',
  'General Roca',
  'General Rodríguez',
  'General San Martín',
  'General Vedia',
  'General Viamonte',
  'General Villegas',
  'General la Madrid',
  'General las Heras',
  'General Ángel Vicente Peñaloza',
  'Gessler',
  'Gobernador Costa',
  'Gobernador Crespo',
  'Gobernador Duval',
  'Gobernador Ing. Valentín Virasoro',
  'Gobernador López',
  'Gobernador Martínez',
  'Gobernador Roca',
  'Godoy Cruz',
  'Godoy',
  'Golondrina',
  'Goya',
  'Gral. Alvear',
  'Gral. Conesa',
  'Gral. Enrique Godoy',
  'Gral. Fdez. Oro',
  'Gral. Roca',
  'Gral. San Martengeneral San Martín',
  'Gran Guardia',
  'Granadero Baigorria',
  'Gregoria Pérez de Denis',
  'Grutly',
  'Guachipas',
  'Guadalupe Norte',
  'Gualjaina',
  'Guaminí',
  'Guanaco Muerto',
  'Guaraní',
  'Guardia Mitre',
  'Guasapampa',
  'Guatimozín',
  'Guatraché',
  'Guaviraví',
  'Guaymallén',
  'Guañacos',
  'Gálvez',
  'Gödeken',
  'Gütemberg',
  'Helvecia',
  'Herlitzka',
  'Hermoso Campo',
  'Hernando',
  'Herradura',
  'Hersilia',
  'Hipatía',
  'Hipólito Irigoyen',
  'Hipólito Yrigoyen',
  'Huacalera',
  'Hualfín',
  'Huanchilla',
  'Huanqueros',
  'Huasa Pampa',
  'Huerta Grande',
  'Hugentobler',
  'Hughes',
  'Huillapima',
  'Huinca Renancó',
  'Huinganco',
  'Humahuaca',
  'Humberto Primo',
  'Humboldt',
  'Hurlingham',
  'Ibarlucea',
  'Ibarreta',
  'Icaño',
  'Idiazabal',
  'Iglesia',
  'Iguazú',
  'Impira',
  'Independencia',
  'Ing. Jacobacci',
  'Ingeniero Chanourdie',
  'Ingeniero Guillermo N. Juárez',
  'Ingeniero Huergo',
  'Ingeniero Luiggi',
  'Inriville',
  'Intendente Alvear',
  'Intiyaco',
  'Iruya',
  'Isla Verde',
  'Isla de Cañas',
  'Isla del Cerrito',
  'Itacaruaré',
  'Italó',
  'Itatí',
  'Ituzaingó',
  'Itá Ibaté',
  'Jacinto Arauz',
  'Jacinto L. Arauz',
  'James Craik',
  'Jardín América',
  'Jesús María',
  'Joaquín V. González',
  'Jose Rafael Gomez',
  'Josefina',
  'José C. Paz',
  'José de San Martín',
  'Jovita',
  'Juan Bernabé Molina',
  'Juan Jorba',
  'Juan José Castelli',
  'Juan Llerena',
  'Juan Pujol',
  'Juan de Garay',
  'Juana Koslay',
  'Juncal',
  'Junín de los Andes',
  'Junín',
  'Justiniano Posse',
  'Justo Daract',
  'Jáchal',
  'Kilómetro 658',
  'La Adela',
  'La Batea',
  'La Brava',
  'La Cabral',
  'La Caldera',
  'La Calera',
  'La Camila',
  'La Candelaria',
  'La Carlota',
  'La Carolina El Potosi',
  'La Cautiva',
  'La Cesira',
  'La Chispa',
  'La Clotilde',
  'La Costa',
  'La Criolla',
  'La Cruz',
  'La Cumbre',
  'La Cumbrecita',
  'La Eduvigis',
  'La Escondida',
  'La Esperanza',
  'La Falda',
  'La Florida y Luisiana',
  'La Francia',
  'La Gallareta',
  'La Granja',
  'La Higuera',
  'La Humada',
  'La Laguna',
  'La Leonesa',
  'La Lucila',
  'La Maruja',
  'La Matanza',
  'La Mendieta',
  'La Merced',
  'La Paisanita',
  'La Palestina',
  'La Pampa',
  'La Paquita',
  'La Para',
  'La Paz',
  'La Pelada',
  'La Penca y Caraguatá',
  'La Plata',
  'La Playa',
  'La Playosa',
  'La Población',
  'La Poma',
  'La Posta',
  'La Puerta',
  'La Punilla',
  'La Punta',
  'La Quiaca',
  'La Quinta',
  'La Ramada y la Cruz',
  'La Rancherita',
  'La Reforma',
  'La Rinconada',
  'La Rubia',
  'La Sarita',
  'La Serranita',
  'La Tigra',
  'La Toma',
  'La Tordilla',
  'La Vanguardia',
  'La Verde',
  'La Viña',
  'Laborde',
  'Labordeboy',
  'Laboulaye',
  'Lafinur',
  'Lago Blanco',
  'Lago Puelo',
  'Laguna Blanca',
  'Laguna Larga',
  'Laguna Limpia',
  'Laguna Naik Neck',
  'Laguna Paiva',
  'Laguna Yema',
  'Lagunita Salada',
  'Lamadrid',
  'Lamarque',
  'Landeta',
  'Lanteri',
  'Lanús',
  'Lapachito',
  'Laprida',
  'Larrechea',
  'Las Acequias',
  'Las Aguadas',
  'Las Albahacas',
  'Las Arrias',
  'Las Avispas',
  'Las Bajadas',
  'Las Bandurrias',
  'Las Breñas',
  'Las Caleras',
  'Las Calles',
  'Las Cañadas',
  'Las Cejas',
  'Las Chacras',
  'Las Coloradas',
  'Las Flores',
  'Las Garcitas',
  'Las Garzas',
  'Las Gramillas',
  'Las Heras',
  'Las Higueras',
  'Las Isletillas',
  'Las Juntas',
  'Las Junturas',
  'Las Lagunas',
  'Las Lajas',
  'Las Lajitas',
  'Las Lomitas',
  'Las Ovejas',
  'Las Palmas',
  'Las Palmeras',
  'Las Parejas',
  'Las Perdices',
  'Las Petacas',
  'Las Peñas Sud',
  'Las Peñas',
  'Las Playas',
  'Las Plumas',
  'Las Rabonas',
  'Las Rosas',
  'Las Saladas',
  'Las Talas',
  'Las Tapias',
  'Las Toscas',
  'Las Tunas',
  'Las Varas',
  'Las Varillas',
  'Las Vertientes',
  'Lavaisse',
  'Lavalle',
  'Lazzarino',
  'Leandro N. Alem',
  'Leguizamón',
  'Lehmann',
  'Leon Rouges y Santa Rosa',
  'Leones',
  'Leoni',
  'Lezama',
  'Libertad',
  'Libertador General San Martín',
  'Limay Mahuida',
  'Lincoln',
  'Llambi Campbell',
  'Lobería',
  'Lobos',
  'Logroño',
  'Loma Alta',
  'Lomas de Vallejos',
  'Lomas de Zamora',
  'Loncopué',
  'Londres',
  'Lonquimay',
  'Loreto',
  'Los Altares',
  'Los Altos',
  'Los Amores',
  'Los Bulacios y los Villagras',
  'Los Cardos',
  'Los Catutos',
  'Los Cedros',
  'Los Cerrillos',
  'Los Chañaritos (C.D. Eje)',
  'Los Chañaritos',
  'Los Chihuidos',
  'Los Chiriguanos',
  'Los Cisnes',
  'Los Cocos',
  'Los Cóndores',
  'Los Frentones',
  'Los Gomez',
  'Los Helechos',
  'Los Hornillos',
  'Los Hoyos',
  'Los Laureles',
  'Los Menucos',
  'Los Miches',
  'Los Mistoles',
  'Los Molinos',
  'Los Molles',
  'Los Nogales',
  'Los Pereyras',
  'Los Perez',
  'Los Pozos',
  'Los Puestos',
  'Los Quirquinchos',
  'Los Ralos',
  'Los Reartes',
  'Los Sarmiento y la Tipa',
  'Los Sosa',
  'Los Surgentes',
  'Los Talares',
  'Los Toldos',
  'Los Varela',
  'Los Zorros',
  'Loventué',
  'Lozada',
  'Luan Toro',
  'Luca',
  'Lucio V. López',
  'Lucio V. Mansilla',
  'Luis Beltran',
  'Luis Palacios',
  'Lujan',
  'Luján de Cuyo',
  'Luján',
  'Luque',
  'Lutti',
  'Luyaba',
  'López',
  'M9Ximo Paz',
  'Macachín',
  'Machagai',
  'Maciel',
  'Magdalena',
  'Maggiolo',
  'Maimará',
  'Mainque',
  'Maipú',
  'Maisonnave',
  'Makallé',
  'Malabrigo',
  'Malagueño',
  'Malargüe',
  'Malena',
  'Malvinas Argentinas',
  'Mamuel Choique',
  'Manfredi',
  'Manuel Garcia Fernandez',
  'Manuela Pedraza',
  'Manzano Amargo',
  'Maquinchao',
  'Maquinista Gallini',
  'Mar Chiquita',
  'Marcelino Escalada',
  'Marcos Juárez',
  'Marcos Paz',
  'Margarita Belén',
  'Margarita',
  'Mariano I. Loza',
  'Mariano Moreno',
  'Marull',
  'María Juana',
  'María Luisa',
  'María Susana',
  'María Teresa',
  'Matilde',
  'Matorrales',
  'Mattaldi',
  'Maua',
  'Mauricio Mayer',
  'Mayor Vicente E. Villafañe',
  'Mayu Sumaj',
  'Mburucuyá',
  'Media Naranja',
  'Medina',
  'Melincué',
  'Melo',
  'Mencuen',
  'Mendiolaza',
  'Mercedes',
  'Merlo',
  'Metileo',
  'Metán',
  'Mi Granja',
  'Miguel Cané',
  'Miguel Riglos',
  'Miguel Torres',
  'Mina Clavero',
  'Mina Pirquitas',
  'Ministro Ramos Mexia',
  'Miraflores',
  'Miramar',
  'Misión Nueva Pompeya',
  'Misión San Francisco de Laishí',
  'Misión Taacaglé',
  'Mocoretá',
  'Moisés Ville',
  'Mojón Grande',
  'Molinos',
  'Monigotes',
  'Monje',
  'Monte Bello',
  'Monte Buey',
  'Monte Caseros',
  'Monte Cristo',
  'Monte Hermoso',
  'Monte Leña',
  'Monte Maíz',
  'Monte Nievas',
  'Monte Oscuridad',
  'Monte Ralo',
  'Monte Vera',
  'Monte de los Gauchos',
  'Monte',
  'Monteagudo',
  'Montecarlo',
  'Montefiore',
  'Monterrico',
  'Montes de Oca',
  'Moreno',
  'Morrison',
  'Morteros',
  'Morón',
  'Municipalidad de Aguilares',
  'Municipalidad de Alderetes',
  'Municipalidad de Banda del Rio Sali',
  'Municipalidad de Bella Vista',
  'Municipalidad de Burruyacu',
  'Municipalidad de Concepcion',
  'Municipalidad de Famailla',
  'Municipalidad de Graneros',
  'Municipalidad de Juan Bautista Alberdi',
  'Municipalidad de Lules',
  'Municipalidad de Monteros',
  'Municipalidad de San Miguel De Tucuman',
  'Municipalidad de Simoca',
  'Municipalidad de Tafi Viejo',
  'Municipalidad de Tafi del Valle',
  'Municipalidad de Trancas',
  'Municipalidad de Yerba Buena',
  'Municipalidad de la Cocha',
  'Municipalidad de las Talitas',
  'Murphy',
  'Mutquín',
  'Mártires',
  'Nahuel Niyeu',
  'Napenay',
  'Naré',
  'Naschel',
  'Naupa Huen',
  'Navarro',
  'Navia',
  'Nazareno',
  'Necochea',
  'Nelson',
  'Neuquén',
  'Nicanor Molinas',
  'Nicolás Bruzzone',
  'Noetinger',
  'Nogoli',
  'Nono',
  'Nueva Galia',
  'Nuevo Torino',
  'Oberá',
  'Obispo Trejo',
  'Octavio Pico',
  'Ojos de Agua',
  'Olaeta',
  'Olavarría',
  'Olegario V. Andrade',
  'Oliva',
  'Olivares de San Nicolás',
  'Oliveros',
  'Onagoity',
  'Oncativo',
  'Ordóñez',
  'P. de los Funes',
  'Pacheco de Melo',
  'Paclín',
  'Palacios',
  'Palma Sola',
  'Palmar Grande',
  'Palo Santo',
  'Palpalá',
  'Pampa Almirón',
  'Pampa Blanca',
  'Pampa Mayo',
  'Pampa del Indio',
  'Pampa del Infierno',
  'Pampayasta Norte',
  'Pampayasta Sud',
  'Pampichuela',
  'Panaholma',
  'Panambí',
  'Papagayos',
  'Parada Pucheta',
  'Parera',
  'Pascanas',
  'Pasco',
  'Paso Aguerre',
  'Paso Flores',
  'Paso Grande',
  'Paso Viejo',
  'Paso de Indios',
  'Paso de la Patria',
  'Paso de los Libres',
  'Paso del Durazno',
  'Paso del Sapo',
  'Patagones',
  'Pavón Arriba',
  'Pavón',
  'Payogasta',
  'Pedro Gómez Cello',
  'Pedro R. Fernández',
  'Pehuajó',
  'Pellegrini',
  'Pergamino',
  'Perico',
  'Perugorría',
  'Perú',
  'Peyrano',
  'Peñas Blancas',
  'Piamonte',
  'Pichanal',
  'Pichi Huinca',
  'Picún Leufú',
  'Piedra del Águila',
  'Pila',
  'Pilar',
  'Pilcaniyeu',
  'Pilo Lil',
  'Pilquiniyeu del Limay',
  'Pilquiniyeu',
  'Pinamar',
  'Pincen',
  'Piquillín',
  'Pirané',
  'Piñero',
  'Plaza Clucellas',
  'Plaza Huincul',
  'Plaza Luxardo',
  'Plaza de Mercedes',
  'Plottier',
  'Pocito',
  'Pomona',
  'Pomán',
  'Porteña',
  'Portugalete',
  'Portón Negro',
  'Posadas',
  'Potrero de Garay',
  'Pozo Borrado',
  'Pozo Nuevo',
  'Pozo de Piedra',
  'Pozo del Molle',
  'Pozo del Tigre',
  'Prahuaniyeu',
  'Presidencia Roca',
  'Presidencia Roque Sáenz Peña',
  'Presidencia de la Plaza',
  'Presidente Perón',
  'Presidente Roca',
  'Profesor Salvador Mazza',
  'Profundidad',
  'Progreso',
  'Providencia',
  'Pueblo Andino',
  'Pueblo Esther',
  'Pueblo Irigoyen',
  'Pueblo Italiano',
  'Pueblo Libertador',
  'Pueblo Marini',
  'Pueblo Muñoz',
  'Puelches',
  'Puelén',
  'Puerta de Corral Quemado',
  'Puerta de San José',
  'Puerto Bermejo',
  'Puerto Esperanza',
  'Puerto Eva Perón',
  'Puerto Madryn',
  'Puerto Piray',
  'Puerto Pirámides',
  'Puerto Rico',
  'Puerto Tirol',
  'Puerto Vilelas',
  'Puesto Viejo',
  'Puesto de Castro',
  'Puesto del Marqués',
  'Pujato Norte',
  'Pujato',
  'Pumahuasi',
  'Punta Indio',
  'Punta del Agua',
  'Purmamarca',
  'Puán',
  'Pérez',
  'Quebracho Herrado',
  'Quehué',
  'Quemú Quemú',
  'Quetrequén',
  'Quili Malal',
  'Quilino',
  'Quilmes y los Sueldos',
  'Quilmes',
  'Quines',
  'Quitilipi',
  'Raco',
  'Rada Tilly',
  'Rafael García',
  'Rafaela',
  'Ramada Paso',
  'Ramallo',
  'Ramayón',
  'Ramona',
  'Ramón Castro',
  'Ranchillos y San Miguel',
  'Rancul',
  'Ranqueles',
  'Rauch',
  'Rawson',
  'Rayo Cortado',
  'Realicó',
  'Reconquista',
  'Recreo',
  'Reducción',
  'Relmo',
  'Renca',
  'Resistencia',
  'Riacho He-He',
  'Riachuelo',
  'Ricardone',
  'Rincon de Treneta',
  'Rinconada',
  'Rincón de los Sauces',
  'Rincón',
  'Rio Chico y Nueva Trinidad',
  'Rio Chico',
  'Rio Colorado',
  'Rio Seco',
  'Rivadavia Banda Norte',
  'Rivadavia Banda Sur',
  'Rivadavia',
  'Rodeíto',
  'Rojas',
  'Roldán',
  'Rolón',
  'Romang',
  'Roque Pérez',
  'Rosales',
  'Rosario Vera Peñaloza',
  'Rosario de Lerma',
  'Rosario de Río Grande',
  'Rosario de la Frontera',
  'Rosario del Saladillo',
  'Rucanelo',
  'Rueda',
  'Rufino',
  'Ruiz de Montoya',
  'Rumipunco',
  'Rìo Colorado',
  'Río Bamba',
  'Río Ceballos',
  'Río Cuarto',
  'Río Grande',
  'Río Mayo',
  'Río Pico',
  'Río Piedras',
  'Río Primero',
  'Río Segundo',
  'Río Tercero',
  'Río de los Sauces',
  'Sa Pereyra',
  'Saavedra',
  'Sacanta',
  'Sagrada Familia',
  'Saguier',
  'Saira',
  'Saladas',
  'Saladero Mariano Cabal',
  'Saladillo',
  'Saldán',
  'Salliqueló',
  'Salsacate',
  'Salsipuedes',
  'Salta',
  'Salto Grande',
  'Salto',
  'Sampacho',
  'Samuhú',
  'San Agustín',
  'San Andres',
  'San Andrés de Giles',
  'San Antonio Oeste',
  'San Antonio de Areco',
  'San Antonio de Arredondo',
  'San Antonio de Litín',
  'San Antonio de Obligado',
  'San Antonio de los Cobres',
  'San Antonio',
  'San Basilio',
  'San Bernardo',
  'San Blas de los Sauces',
  'San Carlos Centro',
  'San Carlos Minas',
  'San Carlos Norte',
  'San Carlos Sud',
  'San Carlos de Bariloche',
  'San Carlos',
  'San Cayetano',
  'San Clemente',
  'San Cosme',
  'San Cristóbal',
  'San Eduardo',
  'San Esteban',
  'San Eugenio',
  'San Fabián',
  'San Felipe y Santa Barbara',
  'San Fernando del Valle de Catamarca',
  'San Fernando',
  'San Francisco de Santa Fe',
  'San Francisco del Chañar',
  'San Francisco',
  'San Genaro',
  'San Gerónimo',
  'San Gregorio',
  'San Guillermo',
  'San Hilario',
  'San Ignacio',
  'San Isidro',
  'San Javier y Yacanto',
  'San Javier',
  'San Jeronimo',
  'San Jerónimo Norte',
  'San Jerónimo Sud',
  'San Jerónimo del Sauce',
  'San Joaquín',
  'San Jorge',
  'San Jose de la Cocha',
  'San Jose del Morro',
  'San José de la Dormida',
  'San José de la Esquina',
  'San José de las Salinas',
  'San José del Rincón',
  'San José',
  'San Juan',
  'San Justo',
  'San Lorenzo',
  'San Luis del Palmar',
  'San Luis',
  'San Marcos Sierras',
  'San Marcos Sud',
  'San Mariano',
  'San Mart',
  'San Martin',
  'San Martín Dos',
  'San Martín de los Andes',
  'San Martín',
  'San Miguel',
  'San Nicolás',
  'San Pablo y Villa Nougues',
  'San Pablo',
  'San Patricio del Chañar',
  'San Pedro Norte',
  'San Pedro de Colalao',
  'San Pedro de Jujuy',
  'San Pedro y San Antonio',
  'San Pedro',
  'San Rafael',
  'San Ramón de la Nueva Orán',
  'San Roque',
  'San Salvador de Jujuy',
  'San Vicente',
  'Sanagasta',
  'Sancti Spiritu',
  'Sanford',
  'Santa Ana',
  'Santa Catalina',
  'Santa Clara de Buena Vista',
  'Santa Clara de Saguier',
  'Santa Clara',
  'Santa Cruz y la Tuna',
  'Santa Elena',
  'Santa Eufemia',
  'Santa Fe',
  'Santa Isabel',
  'Santa Lucia',
  'Santa Lucía',
  'Santa Margarita',
  'Santa María Centro',
  'Santa María Norte',
  'Santa María de Punilla',
  'Santa María',
  'Santa Rosa de Calamuchita',
  'Santa Rosa de Calchines',
  'Santa Rosa de Leales y L. Blanca',
  'Santa Rosa de Río Primero',
  'Santa Rosa',
  'Santa Sylvina',
  'Santa Teresa',
  'Santa Victoria Este',
  'Santa Victoria Oeste',
  'Santiago Temple',
  'Santiago de Liniers',
  'Santo Domingo',
  'Santo Pipo',
  'Santo Tomás',
  'Santo Tomé',
  'Santurce',
  'Sarah',
  'Sargento Cabral',
  'Sargento Moya',
  'Sarmiento',
  'Sastre',
  'Saturnino María Laspiur',
  'Sauce Arriba',
  'Sauce Viejo',
  'Sauce',
  'Saujil',
  'Sauzal Bonito',
  'Sebastián Elcano',
  'Seclantás',
  'Seeber',
  'Segunda Usina',
  'Senillosa',
  'Serodino',
  'Serrano',
  'Serrezuela',
  'Sierra Colorada',
  'Sierra Grande',
  'Sierra Paileman',
  'Siete Palmas',
  'Silva',
  'Silvio Pellico',
  'Simbolar',
  'Sinsacate',
  'Soldado Maldonado',
  'Soldini',
  'Soledad',
  'Soutomayor',
  'Speluzzi',
  'Sta Rosa del Conlara',
  'Suardi',
  'Subteniente Perín',
  'Suco',
  'Suipacha',
  'Sunchales',
  'Susana',
  'Susques',
  'Tabay',
  'Taco Pozo',
  'Taco Ralo',
  'Tacuarendí',
  'Tacural',
  'Tacurales',
  'Tala Cañada',
  'Tala Huasi',
  'Talaini',
  'Talita',
  'Tancacha',
  'Tandil',
  'Tanti',
  'Tapalqué',
  'Tapebicuá',
  'Tapia',
  'Tapso',
  'Taquimilán',
  'Tartagal',
  'Tatacuá',
  'Tecka',
  'Telsen',
  'Telén',
  'Teniente Berdina',
  'Teodelina',
  'Theobald',
  'Ticino',
  'Tigre',
  'Tilcara',
  'Tilisarao',
  'Timbúes',
  'Tinoco',
  'Tinogasta',
  'Toay',
  'Toba',
  'Tolar Grande',
  'Toledo',
  'Tolhuin',
  'Tomás Manuel Anchorena',
  'Tordillo',
  'Tornquist',
  'Toro Pujio',
  'Tortugas',
  'Tosno',
  'Tosquita',
  'Tostado',
  'Totoras',
  'Traill',
  'Trelew',
  'Trenel',
  'Trenque Lauquen',
  'Tres Arroyos',
  'Tres Capones',
  'Tres Cruces',
  'Tres Isletas',
  'Tres Lagunas',
  'Tres Lomas',
  'Tres de Febrero',
  'Trevelín',
  'Tricao Malal',
  'Trinidad',
  'Tránsito',
  'Tuclame',
  'Tumbaya',
  'Tunuyán',
  'Tupungato',
  'Tío Pujio',
  'Ucacha',
  'Ullum',
  'Unanue',
  'Union',
  'Unquillo',
  'Uranga',
  'Uriburu',
  'Urundel',
  'Ushuaia',
  'V, Gral, Roca',
  'V, de Praga',
  'V, de la Quebrada',
  'Valcheta',
  'Valle Azul',
  'Valle Fértil',
  'Valle Grande',
  'Valle Hermoso',
  'Valle Viejo',
  'Valle de Anisacate',
  'Vaqueros',
  'Varvarco - Invernada Vieja',
  'Veinticinco de Mayo',
  'Venado Tuerto',
  'Vera y Pintado',
  'Vera',
  'Viamonte',
  'Vicente López',
  'Victorica',
  'Vicuña Mackenna',
  'Videla',
  'Viedma',
  'Vila',
  'Villa Allende',
  'Villa Amancay',
  'Villa Amelia',
  'Villa Ana',
  'Villa Ascasubi',
  'Villa Berthet',
  'Villa Candelaria Norte',
  'Villa Carlos Paz',
  'Villa Cañás',
  'Villa Cerro Azul',
  'Villa Ciudad Parque los Reartes',
  'Villa Ciudad de América',
  'Villa Concepción del Tío',
  'Villa Constitución',
  'Villa Cura Brochero',
  'Villa Curi Leuvú',
  'Villa Dolores',
  'Villa Dos Trece',
  'Villa Elisa',
  'Villa Eloísa',
  'Villa Escolar',
  'Villa Fontana',
  'Villa General Belgrano',
  'Villa Gesell',
  'Villa Giardino',
  'Villa Gobernador Gálvez',
  'Villa Guillermina',
  'Villa Gutiérrez',
  'Villa Huidobro',
  'Villa Larca',
  'Villa Llanquin',
  'Villa María',
  'Villa Mercedes',
  'Villa Minetti',
  'Villa Mirasol',
  'Villa Mugueta',
  'Villa Nueva',
  'Villa Olivari',
  'Villa Padre Monti',
  'Villa Parque Santa Ana',
  'Villa Parque Siquiman',
  'Villa Pehuenia',
  'Villa Quillinzo',
  'Villa Quinteros',
  'Villa Regina',
  'Villa Rossi',
  'Villa Rumipal',
  'Villa Río Bermejito',
  'Villa Río Icho Cruz',
  'Villa San Esteban',
  'Villa San Isidro',
  'Villa San José',
  'Villa Santa Cruz del Lago',
  'Villa Saralegui',
  'Villa Sarmiento (G.R.)',
  'Villa Sarmiento (S. A.)',
  'Villa Traful',
  'Villa Trinidad',
  'Villa Tulumba',
  'Villa Valeria',
  'Villa Vil',
  'Villa Yacanto',
  'Villa de Chicligasta',
  'Villa de Leales',
  'Villa de María',
  'Villa de Pocho',
  'Villa de Soto',
  'Villa de las Rosas',
  'Villa del Carmen',
  'Villa del Dique',
  'Villa del Nahueve',
  'Villa del Prado',
  'Villa del Puente Picún Leufú',
  'Villa del Rosario',
  'Villa del Totoral',
  'Villa el Chacay',
  'Villa el Chocón',
  'Villa la Angostura',
  'Villa la Bolsa',
  'Villa los Aromos',
  'Villa los Patos',
  'Villa Ángela',
  'Villada',
  'Villarino',
  'Vinalito',
  'Vinchina',
  'Virginia',
  'Vista Alegre',
  'Volcán',
  'Vértiz',
  'Washington',
  'Wenceslao Escalante',
  'Wheelwright',
  'Winifreda',
  'Yala',
  'Yaminué',
  'Yanima',
  'Yapeyú',
  'Yataytí Calle',
  'Yavi',
  'Yerba Buena',
  'Yuto',
  'Zanjitas',
  'Zapala',
  'Zavalla',
  'Zenón Pereyra',
  'Zonda',
  'Zárate',
  'Álvarez',
  'Ñanducita',
  'Ñorquinco',
];
